# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

#theme: alembic-jekyll-theme

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-seo-tag
- jekyll-mentions
- jekyll-remote-theme
- jemoji
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-paginate
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache


# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
author: Sérgio Polo # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Sérgio Polo # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.linkedin.com/in/sergio-lp
    - https://github.com/sergio-lp
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/img/bg.jpg" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: pt-BR # Set the site language
title: "Sérgio Polo" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/favicon.ico" # Site logo, also used in jekyll-seo-tag
description: "Sérgio Lourenço Polo Filho | Graduando em Medicina (FCM - Unicamp), entusiasta em desenvolvimento Android e apaixonado por tecnologia." # Site description and default description, also used in jekyll-seo-tag
url: "https://sergio-lp.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
email: "sergio_lpf@outlook.com"
google_analytics: "G-0JQHQ16G1L"
# disqus:
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: 'favicon-16x16.png'
  32: 'favicon-32x32.png'
#  96: '/assets/logos/logo@96px.png'
#  120: '/assets/logos/logo@120px.png'
#  144: '/assets/logos/logo@144px.png'
#  180: '/assets/logos/logo@180px.png'
#  512: '/assets/logos/logo@512px.png'
#  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Projetos
  url: /projects/
- title: Contato
  url: /contact/
- title: Github
  url: https://github.com/sergio-lp
- title: Assinatura eletrônica
  url: /signature/
- title: Sistema UBS
  url: /consulta-ubs//

navigation_footer:
- title: Made with jekyll and Alembic
  url: https://jekyllthemes.io/theme/alembic

# Remote Theme
remote_theme: daviddarnes/alembic@main
#theme: alembic-jekyll-theme
